spring:
  #configuracion base de datos
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cursos?serverTimezone=UTC
    username: root
    password: root
  #propiedades para que hibernate cree adecuadamente las instrucciones SQL
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  #para que swagger resuelva correctamente los paths internos
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher  
#registro de servicio en eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    #descubrimiento de servicios en eureka 
    register-with-eureka: true
  instance:
    #para balanceado de peticiones: cambiar valor de instance-id y server.port
    instance-id: servicio-cursos-1
server:
  port: 8080
